[input]
rootFile = /home/mutu/Desktop/RTE/LAPPDBeamCluster_6089.root
mrdFile  = ./MRDInfo.txt
useMC     = false
[output]
rootFile = ./CCFiltered6089.root
writeMode = filtered

[cuts]
requireLAPPD            = true

# Quality cuts
beamOK                  = true
brfWindow               = false
ppsMissing              = true
ppsIntervalSec = 5
#Physics cuts
pairedEvent             = true
promptPMTCluster        = true
highQualityPMTCluster   = true
mrdTrackReconstructed   = true
tankMRDCoinc            = true
muonTopology            = false
noVeto                  = false

[cutValues]
promptWindowMax  = 2000.0
chargeBalanceMax = 0.2

mrdTimeWindow  = 30.0
mrdMinSideHits = 2
mrdMinTopHits  = 2

# for muonTopology cut 
lappdNeighborPMTIDs = 462,428,406,412
lappdNeighborPMTPEThreshold = 5.0 

#for brfWindow cut
brfMin = 5.0
brfMax = 30.0
