[input]
rootFile  = /home/mutu/Desktop/Fermilab-simulationStided/narrow-bunch-from-amala/ANNIETree_MC.root
mrdFile   = ./MRDInfo.txt
useMC     = true

[output]
rootFile = filtered_MC.root

[cuts]
requireLAPPDMeta = false
useSelectedLAPPD = false

# Quality cuts
beamOK = false
brfWindow = false
ppsMissing = false

# Physics cuts
pairedEvent = true
promptPMTCluster = true
highQualityPMTCluster = true
mrdTrackReconstructed = true
tankMRDCoinc = true
muonTopology = false
noVeto = false

[cutValues]
promptWindowMax = 2000.0
chargeBalanceMax = 0.2
mrdTimeWindow = 30.0
mrdMinSideHits = 2
mrdMinTopHits = 2
pmtPEThreshold = 5.0
brfMin = 5.0
brfMax = 30.0
