[input]
rootFile  = ../narrow-bunch-from-amala/R6089_withPPS.root
mrdFile   = ./MRDInfo.txt
pmtFile   = ./PMTInfo.txt
lappdFile = ./LAPPDInfo.txt

#must remain false (MC uses a separate config file)
useMC = false 

[output]
pdfFileName = EventDisplay.pdf
[event]
#Set to -1 to process all events in the three
maxEventNum = 5
[tankPMT]
clusterTimeMin = 0.
clusterTimeMax = 2000.
tankPMTsPEThreshold = 30.
[tankLAPPD]
lappdHitTimeMin = 0.
lappdHitTimeMax = 250.
lappdHitThreshold = 0
[mrd]
mrdDisplayWindow = 30.
dtMRDPMTMin = 700.
dtMRDPMTMax = 800.
dtMRDPMTHistPeak = 750.
[fmv]
dtFMVPMTMin = 800.
dtFMVPMTMax = 860.
dtFMVPMTHistPeak = 830.
