[input]
rootFile  = /home/mutu/Desktop/Fermilab-simulationStided/ANNIETree_MC.root
mrdFile   = ./MRDInfo.txt
pmtFile   = ./PMTInfo.txt
lappdFile = ./MCLAPPDInfo.txt

#must remain true (data uses a separate config file)
useMC = true 

[output]
pdfFileName = EventDisplay.pdf
[event]
maxEventNum = 5
[tankPMT]
clusterTimeMin = 0.
clusterTimeMax = 2000.
tankPMTsPEThreshold = 30.
[tankLAPPD]
lappdHitTimeMin = 0.
lappdHitTimeMax = 250.
lappdHitThreshold = 0
[mrd]
mrdDisplayWindow = 30.
dtMRDPMTMin = -10.
dtMRDPMTMax = 10.
dtMRDPMTHistPeak = 0.
[fmv]
dtFMVPMTMin = -10.
dtFMVPMTMax = 10.
dtFMVPMTHistPeak = 0.
